# fly.toml app configuration file generated for mini-games on 2025-10-14T08:14:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mini-games'
primary_region = 'arn'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
